services:
  - type: web
    name: smart-attendance
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://attendanceuser:Likhitha0910@cluster0.i70a7eo.mongodb.net/attendanceDB?retryWrites=true&w=majority